### ISSUE TITLE
Crashing due to DivisionOfZero 

### ISSUE THREAD

**Issue by MAGabriel0220** [nuggetcatsoftware/Alpha-Mouse#1]
While running, 
IF hands are no longer detected such that the framerate has skyrocketed to an infinite amount where it shows this error
```
Traceback (most recent call last):
  File "handmouse.py", line 77, in <module>
ZeroDivisionError: float divmod()
```

**Comment by privacyrespected** [comment]
This is solved in the new release by removing the framerate as it is solely used for debugging anyways
